# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbrief',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userbrief',
            old_name='user_pswd',
            new_name='pswd',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='user_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='user_intro',
            new_name='intro',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='user_img',
        ),
        migrations.AddField(
            model_name='userbrief',
            name='head_img',
            field=models.CharField(default='NULL', max_length=255),
            preserve_default=False,
        ),
    ]
