# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20171030_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('video', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('img', models.CharField(max_length=255)),
                ('site_id', models.IntegerField()),
                ('movie_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SiteInRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_index', models.IntegerField()),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Route')),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Site')),
            ],
        ),
        migrations.RenameField(
            model_name='userbrief',
            old_name='user_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='user_label',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='label',
            field=models.TextField(default='No labels'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userbrief',
            name='user_follow',
            field=models.ManyToManyField(to='main_page.UserBrief'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='intro',
            field=models.TextField(default='No introductions'),
        ),
        migrations.AddField(
            model_name='route',
            name='sites',
            field=models.ManyToManyField(through='main_page.SiteInRoute', to='main_page.Site'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='route_follow',
            field=models.ManyToManyField(to='main_page.Route'),
        ),
    ]
