# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_auto_20171030_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='site_id',
        ),
        migrations.AddField(
            model_name='plot',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_page.Movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plot',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_page.Site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='intro',
            field=models.TextField(default='TA 还没有添加任何介绍'),
        ),
    ]
