# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 02:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_img', models.CharField(max_length=255)),
                ('intro', models.TextField(default='TA 还没有添加任何介绍')),
                ('label', models.TextField(default='TA 还没有添加任何标签')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('route_follow', models.ManyToManyField(to='main_page.Route')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_follow', models.ManyToManyField(related_name='follow_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
