# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 05:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20171105_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_follow',
            field=models.ManyToManyField(related_name='follow_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
