# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20171106_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='label',
            field=models.TextField(default='TA 还没有添加任何标签'),
        ),
    ]
