# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20171106_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='route_follow',
            field=models.ManyToManyField(to='main_page.Route'),
        ),
    ]
